### ISSUE TITLE
Nit: license doesn't match file headers.

### ISSUE THREAD

**Issue by aaroncrespo** [RLovelett/vscode-swift#10]

**Comment by RLovelett** [comment]
[This is the only place that I could find this.](https://github.com/RLovelett/vscode-swift/blob/726fa21e9a3cac70b7c2b1e7704f7910ca38f471/vscode-swift-language-server/src/server.ts#L1-L4) Did you have others?

**Comment by aaroncrespo** [comment]
Yeah I didn't do an exhaustive search might be the only one.
