### ISSUE TITLE
Add Changelog.md

### ISSUE THREAD

**Issue by aaroncrespo** [RLovelett/vscode-swift#18]
Missing entries for 4.0, 5.0

**Comment by aaroncrespo** [comment]
marketplace readme already has a change log, maybe it would get forgotten

**Comment by RLovelett** [comment]
I'm going to close this for now since I'm putting a "change log" on both the [releases page](https://github.com/RLovelett/vscode-swift/releases) and [README.md](https://github.com/RLovelett/vscode-swift/blob/master/README.md#release-notes).
