### ISSUE TITLE
Does it support Swift 3?

### ISSUE THREAD

**Issue by chika-kasymov** [RLovelett/vscode-swift#21]
I'm running `macOS Sierra 10.12.1` and `Swift 3`. I installed `SourceKitten 0.14.1` and added your extension to VCS, but auto completion not working.

**Comment by RLovelett** [comment]
I can confirm the same on my end. It might be that SourceKitten has changed its output format or something.

I'm looking to improve this behavior significantly by refactoring most of the support. I won't close this but I will also say this is probably a few weeks away from being resolved.

Thank you for your patience.

**Comment by lsunsi** [comment]
+1 here. I'm excited to try this out. I have same versions as @chika-kasymov

**Comment by piyushchauhan2011** [comment]
Yeah, it's also not working for me too with Swift 3, latest vscode and sourcekitten installed. Would be nice to have as really excited about it. Thanks 👍

**Comment by se-rg-os** [comment]
Hey, 
autocompletion does not work for me unfortunately, as well as searching for symbols.
I have config like:

- macOS Sierra 10.12.1
- VS Code 1.7.2
- sourcekitten 0.15.0
- Swift 2.x

**Comment by RLovelett** [comment]
[Just released a new version that _should_ hopefully bring support to Swift 3.1 and further.](https://github.com/RLovelett/vscode-swift/releases/tag/0.1.0)
