### ISSUE TITLE
Swift 3.0 - Linux support?

### ISSUE THREAD

**Issue by ram0811** [RLovelett/vscode-swift#22]
Sourcekit now builds on Linux. https://github.com/jpsim/SourceKitten/issues/179

**Comment by RLovelett** [comment]
I am aware. I've been following the development of both SourceKit and SourceKitten on Linux very closely. While it does _compile_ on Linux now it is not compiled by default on Linux. Meaning that the necesary libraries are not distributed with the binary packages and still have to be generated seperately (this is among the reasons why SourceKitten tests in a Docker image).

Point is there is a lot more necessary to get from where we are to where we need to be. The community gets closer everyday and I am following those developments. Sometimes even contributing to that development.

Rest assured, I plan to support it in this plug-in the moment it is ready.

**Comment by ram0811** [comment]
hehe :) thanks bro you're awesome!
