### ISSUE TITLE
Adopt SnippetString API

### ISSUE THREAD

**Issue by jrieken** [RLovelett/vscode-swift#24]
With the December release VS Code will have real API to define a CompletionItem that is inserted as snippet, for details see https://github.com/Microsoft/vscode/issues/3210. 

In short, we now support a subset of the more common TextMate syntax: `$1`, `$2` etc define tabstops, `${1:value}` and `${2:this is${3:nested}}` placeholders, and `$0` is for the final tabstop. 

The API for this is contained in a new type [`SnippetString`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2035). It can be used as the `insertText` of a [CompletionItem](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2364).

During a transition phase we will still support the internal, unspecified snippet syntax your extension is using but eventually remove it (roughly 2 or 3 milestones from now). 

The language server protocol supports the SnippetString in its next-branch - see https://github.com/Microsoft/vscode/issues/15577#issuecomment-262160802

**Comment by RLovelett** [comment]
@jrieken the link you provided to `SnippetString` seems broken. Can you provide a permanent URL?

**Comment by jrieken** [comment]
Today it is here: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2073. Rule is to check with the `vscode.d.ts`-file which is the only source of API definitions

**Comment by jrieken** [comment]
Fyi - the deprecation of the internal snippet syntax will happen soon (March/April release)

**Comment by RLovelett** [comment]
[AFAICT I've adopted this in the language server that drives this extension](https://github.com/RLovelett/langserver-swift/blob/master/Tests/LanguageServerProtocolTests/Functions/ConvertTests.swift#L16-L20).

Are there any specific steps I can take to ensure my assumption is correct?

**Comment by jrieken** [comment]
Looks like is complies with the snippet grammar: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.md#L28. How do you pass on this things? Unless they are marked to be a SnippetString they will be interpreted as is
