### ISSUE TITLE
Windows / Linux support

### ISSUE THREAD

**Issue by matyasf** [RLovelett/vscode-swift#26]
Does this support Windows or Linux?      
If not please state it in the readme, its confusing.    

thanks.

**Comment by RLovelett** [comment]
As of right now: no it does not. Though Linux is on the roadmap.

Not as sure about Windows.

**Comment by RLovelett** [comment]
I've updated the [Linux section in the README](https://github.com/RLovelett/vscode-swift#linux) to reflect the current state of Linux support.
