### ISSUE TITLE
Super high energy consumption on MacBook 

### ISSUE THREAD

**Issue by daizhirui** [RLovelett/vscode-swift#36]
I build a release version LanguageServer and put it in /usr/local/bin, but once vscode invokes LanguageServer, the CPU reaches full speed and my MacBook becomes very hot. Also, everytime vscode reloads itself, an old LanguageServer is not closed and it launches a new LanguageServer.
<img width="565" alt="image" src="https://user-images.githubusercontent.com/26495795/40531830-c10e7758-5ffd-11e8-917e-dfb67538e9d9.png">

**Comment by RLovelett** [comment]
[This should be resolved now.](https://github.com/RLovelett/langserver-swift/pull/46)
