### ISSUE TITLE
Error on hover

### ISSUE THREAD

**Issue by indiejames** [RLovelett/vscode-swift#38]
I am attempting to use your extension, but getting the following error when I hover over a symbol:

> [Error - 10:12:32 PM] Request textDocument/hover failed.
>   Message: Could not find /Users/jnorton/Documents/Xcode/Barriers/Barriers/GameViewController.swift in the workspace.
>   Code: -32099 

I have compiled the language server successfully.

**Comment by RLovelett** [comment]
Is this a SwiftPM project?

**Comment by indiejames** [comment]
No, it is not. It is an iOS project. I have tried creating a simple iOS project that use SwiftPM for the project dependencies (not for the project targets) as described [here](https://github.com/j-channings/swift-package-manager-ios), but that project has the same problem.

**Comment by RLovelett** [comment]
At this time I only am supporting SwiftPM packages (as that is a large task in its own right). So at least for now I'm going to call this a wontfix and close.

I may revisit this in the future once I finish the Linux implementation.

Thank you for the report.

**Comment by indiejames** [comment]
Thanks for your work on this. You might want to add a mention to the README that you only support SwiftPM projects (unless I somehow missed that).

**Comment by RLovelett** [comment]
I think that's a great point and one that I will look into correcting. Though someone has messaged me on Gitter and said they're working on a PR to add support for non-SPM projects so I may just hold off and see what comes of that.
