### ISSUE TITLE
Problem when trying to build the `vscode-swift` clone.

### ISSUE THREAD

**Issue by carlca** [RLovelett/vscode-swift#39]
```
macOS 10.13.6
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
VSCode Version 1.25.0-insider (1.25.0-insider)
```

Hello, I've been following the steps on the main page here, and I've completed the `XCode` bit and made a note of the `TARGET_BUILD_DIR`. 

When I come to load the `src/extension.ts` file, I notice straight away there are 3 red squiggles in the `import` section, presumably indicating unresolved imports...

![screen shot 2018-06-22 at 16 52 26](https://user-images.githubusercontent.com/260612/41786193-c0270b70-763c-11e8-85d3-81729abbc79a.png)

Then, after pasting in the `TARGET_BUILD_DIR` value, I try the build process but I get the notification message...

![screen shot 2018-06-22 at 16 57 17](https://user-images.githubusercontent.com/260612/41786436-6289bd72-763d-11e8-90b1-b27dff7b399a.png)

I realise it's early days for this tool, and that your priorities are probably with the Linux side of things at the moment, but do you have any idea what the problems are here? Thanks!

**Comment by carlca** [comment]
Not to worry! I tweaked the `tasks.json` to have `"version": "0.2.0",` and it worked. I was expecting a reassuring fanfare and some flashing lights to indicate that the thing had built. Instead, I checked the `TARGET_BUILD_FOLDER` and there was stuff inside of it.

Back to the documentation to work out what to do with it!

**Comment by RLovelett** [comment]
Thank you @carlca let me know if there are some concrete changes I need to make to the README docs.

**Comment by carlca** [comment]
Talking of which! You say in the README...

"Once this is complete you should be able to open the VSCode debugger and select Launch Extension. This should start both the language server (Xcode/Swift) and the extension (VScode/TypeScript) in debug mode.'

I've tried opening the VSCode debugger and I cannot see any option called `Launch Extension`, plu I get the error message in VSCode...

![screen shot 2018-06-22 at 17 26 01](https://user-images.githubusercontent.com/260612/41787790-68eb56a4-7641-11e8-91e2-7d63ab2a3295.png)

Presumably, this has something to do with the fact that after building the LangServer, I didn't do anything to let VSCode know that it had to use said LangServer. 

I may be missing a point, or several, but I think this indicates that the docs could be a little more detailed so that those amongst us with not so much knowledge of VSCode will not run into these stumbling blocks!

**Comment by RLovelett** [comment]
It seems that you did not correctly edit the `extension.ts` file. If it is looking for that file then you did not correctly set the executable path.

**Comment by carlca** [comment]
I haven't edited the `extension.ts` file at all. Was I supposed to? Also, was I supposed to reload the rebuild VSCode-Swift extension into VSCode? I didn't see any instructions about this either. By `set the executable path` do you mean when I pasted the `TARGET_BUILD_FOLDER` into VSCode?

**Comment by carlca** [comment]
Also, I've looked in `/usr/local/bin` and there is no file called `LanguageServer` there.

**Comment by RLovelett** [comment]
>  haven't edited the extension.ts file at all. Was I supposed to?

I don't know. [I thought you were trying to debug the extension](https://github.com/RLovelett/vscode-swift#debug-and-development). I made that assumption since you were messing with `TARGET_BUILD_FOLDER` where opening the `extension.ts` file and the only place that is referenced in the README is in the debug section. If your not trying to debug the extension then don't mess with `TARGET_BUILD_FOLDER` or really anything in that section.

> Also, was I supposed to reload the rebuild VSCode-Swift extension into VSCode?

I do not know what this means and I am beginning to feel like I do not understand what you are trying to achieve.

> Also, I've looked in /usr/local/bin and there is no file called LanguageServer there.

Right, that makes sense. You need to build the language server and install it there. As discussed in the [requirements](https://github.com/RLovelett/vscode-swift#requirements) section of the README.

**Comment by carlca** [comment]
Your documentation quite clearly says...
```
This extension requires Swift to be installed on your system. It also requires a Swift language server be installed as well. By default the extension looks for the language server to be installed at /usr/local/bin/LanguageServer (though this behavior is configurable).
```
So, what I am trying to achieve is quite simply to install the `Swift Language Server` to enable me to use the VSCode-Swift extension. I'm not trying to do anything exotic with it, just use it!

*** ALERT - PROBLEM SOLVED ***

I hadn't realised that the LanguageServer had a separate Github page and that building it was as simple as typing `make build`. I had mistaken the debugging instructions for the LanguageServer for the basic documentation. 

Apologies that my confusion caused you some confusion. Hopefully, this clears it up. I'll report back in a few moments...
