### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by longjianjiang** [RLovelett/vscode-swift#41]
![屏幕快照 2019-05-07 下午4 46 21](https://user-images.githubusercontent.com/15277239/57286349-a638b000-70e7-11e9-8adf-c33a833c0cf0.png)

I tried build it many times and searched some repo, but i haven't found a version that i can use to debug.

May i have your debug build of libdispatch made. Thanks!

**Comment by RLovelett** [comment]
I don't have this build anymore and realistically I should have archived this repo. You should be using https://github.com/apple/sourcekit-lsp instead. It has a VSCode extension as well.
